[package]
name = "sillydrageon"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
lorax = { path = "lorax" }
dialect = { path = "dialect" }

[dev-dependencies]
test_each_file = "0.3.4"
proptest = "1.6.0"
